---
image: docker:latest

services:
  - docker:dind

before_script:
  - apk update && apk add --no-cache
    python3-dev py3-pip gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh
  - docker info
  - python3 --version
  - python3 -m pip install ansible molecule[docker] ansible-lint
  - ansible --version
  - molecule --version

molecule:
  stage: test
  script:
    - molecule test
