---
- name: Include fact generation
  ansible.builtin.import_tasks: fact.yml

- name: Include family specific variables
  ansible.builtin.include_vars: "family-{{ _init_os_family }}.yml"

- name: Include distro variables
  ansible.builtin.include_vars: "distro-{{ _init_distribution }}-{{ _init_distribution_version }}.yml" # yamllint disable-line rule:line-length

- name: Include distro tasks
  ansible.builtin.include_tasks: setup-{{ _init_distribution }}.yml

- name: Install ansible bootstrap packages
  ansible.builtin.package:
    name: "{{ _packages_ansible_bootstrap }}"
    state: present

- name: Generate packages list
  ansible.builtin.set_fact:
    _packages: "{{ _packages + _packages_os }}"
  when:
    - (_packages_os is defined) or (_packages_os | length > 0)

- name: Install packages
  ansible.builtin.package:
    name: "{{ _packages }}"
    state: present

- name: Install packages backports
  ansible.builtin.apt:
    name: "{{ _packages_backports }}"
    state: present
    default_release: "{{ ansible_distribution_release }}-backports"
  when:
    - ansible_os_family == "Debian"
    - _packages_backports is defined
    - _packages_backports | length > 0

- name: Ensure group "init_groups" exists
  ansible.builtin.group:
    name: "{{ item.group_name }}"
    gid: "{{ item.group_gid | default(omit) }}"
    state: present
  loop: "{{ init_groups }}"

- name: Ensure group "user_name" exists
  ansible.builtin.group:
    name: "{{ item.user_name }}"
    state: present
  loop: "{{ init_users | flatten(levels=1) }}"

- name: Create default users
  ansible.builtin.user:
    name: "{{ item.user_name }}"
    append: true
    comment: "{{ item.user_comment }}"
    expires: -1
    generate_ssh_key: true
    groups: "{{ item.user_groups | default(item.user_name) }}"
    home: "{{ item.user_home }}"
    password: "{{ item.user_password }}"
    shell: "{{ item.user_shell | default('/bin/bash') }}"
    ssh_key_bits: 4096
    ssh_key_comment: fake_key
    ssh_key_file: .ssh/id_rsa
    ssh_key_type: rsa
    state: present
    uid: "{{ item.user_uid | default(omit) }}"
    update_password: on_create
  loop: "{{ init_users | flatten(levels=1) }}"

- name: Copy ssh banner
  ansible.builtin.copy:
    src: banner.txt
    dest: /etc/banner.txt
    owner: root
    group: root
    mode: 0640

- name: Ensure banner is enabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^#Banner none$"
    line: "Banner /etc/banner.txt"
    backrefs: true
  notify: RESTART_SSHD
