---
- name:         Ensure EPEL repository is enabled
  yum:
    name:       epel-release
    state:      present
    enablerepo: extras

- name:         Install the 'Development tools' package group
  yum:
    name:       "@Development tools"
    state:      present
