---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian9
    hostname: debian9
    image: pandemonium1986/debian9:latest
    pull: True
    pre_build_image: True
    tty: True
    override_command: False
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
